/**
 * @type {{
 *    CHOOSE_FOLDER: string,
 *    NO_SELECTION: string,
 *    LABEL_DIALOG_WINDOW: string,
 *    LABEL_ARTBOARD_WIDTH: string,
 *    LABEL_ARTBOARD_HEIGHT: string,
 *    LABEL_COL_COUNT: string,
 *    LABEL_ROW_COUNT: string,
 *    LABEL_ARTBOARD_SPACING: string,
 *    LABEL_SCALE: string,
 *    LABEL_FILE_NAME: string,
 *    LABEL_FILETYPES: string,
 *    LABEL_LOGGING: string,
 *    FILETYPE_SVG: string,
 *    FILETYPE_AI: string,
 *    FILETYPE_EPS: string,
 *    FILETYPE_PDF: string,
 *    BUTTON_CANCEL: string,
 *    BUTTON_OK: string,
 *    DOES_NOT_EXIST: string,
 *    LAYER_NOT_CREATED: string,
 *    LABEL_SRC_FOLDER: string,
 *    LABEL_CHOOSE_FOLDER: string,
 *    LABEL_INPUT: string,
 *    LABEL_SIZE: string,
 *    LABEL_OUTPUT: string,
 *    SORT_FILELIST_FAILED: string,
 *    LABEL_SORT_ARTBOARDS: string,
 *    PROGRESS: string,
 *    IMPORTING_FILE: string,
 *    ERROR: string,
 *    ERROR_IN_FILE: string,
 *    CENTERING_OBJ: string
 * }}
 */
!(function(global) {
    var Strings = {
        CHOOSE_FOLDER          : 'Please choose your Folder of files to merge',
        NO_SELECTION           : 'No selection',
        LABEL_DIALOG_WINDOW    : 'Merge SVG Files',
        LABEL_ARTBOARD_WIDTH   : 'Artboard Width:',
        LABEL_ARTBOARD_HEIGHT  : 'Artboard Height:',
        LABEL_COL_COUNT        : 'Columns:',
        LABEL_ROW_COUNT        : 'Rows:',
        LABEL_ARTBOARD_SPACING : 'Artboard Spacing:',
        LABEL_SCALE            : 'Scale:',
        LABEL_FILE_NAME        : 'File Name:',
        LABEL_FILETYPES        : 'File Types:',
        LABEL_LOGGING          : 'Logging?',
        FILETYPE_SVG           : 'SVG',
        FILETYPE_AI            : 'AI',
        FILETYPE_EPS           : 'EPS',
        FILETYPE_PDF           : 'PDF',
        BUTTON_CANCEL          : 'Cancel',
        BUTTON_OK              : 'Ok',
        DOES_NOT_EXIST         : ' does not exist',
        LAYER_NOT_CREATED      : 'Could not create layer. ',
        LABEL_SRC_FOLDER       : 'Source Folder',
        LABEL_CHOOSE_FOLDER    : 'Choose Folder',
        LABEL_INPUT            : 'Input',
        LABEL_SIZE             : 'Size',
        LABEL_OUTPUT           : 'Output',
        SORT_FILELIST_FAILED   : 'Could not sort the file list',
        LABEL_SORT_ARTBOARDS   : 'Sort Artboards?',
        PROGRESS               : 'Progress',
        IMPORTING_FILE         : 'Importing file ',
        ERROR                  : 'Error',
        ERROR_IN_FILE          : 'Error in `doc.groupItems.createFromFile` with file `',
        CENTERING_OBJ          : "Centering object ",
        SELECT_ONE_FILETYPE    : "Please select at least one file type."
    };

    global.Strings = Strings;
})(this);
